:PROPERTIES:
:ID:       DE82167B-D7B4-4178-B63E-6D367B15F897
:END:
#+title: macos



* Softwares

** VirtualBox
After you successfully installed a Linux server in VirtualBox, you can =ssh= into your Linux server from your Mac terminal. Before the =ssh= command, make the network setting is "Bridged Adapter" (VirtualBox -> Settings -> Network -> Bridged Adapter).




** Emacs
** QQ (App Store)
** WeChat (App Store)
** PyCharm
** Anaconda
** Messenger (App Store)
** TeX Live
** Zoom
** Pages (App Store)
** Keynote (App Store)
** Mathpix
** Firefox
** Homebrew
** Google Chrome
** Adobe Acrobat Reader
** Skim
https://skim-app.sourceforge.io

This application is used for lookup of latex source code in Emacs.

** WPS Office(App Store)
* Settings
** Screenshot
Launchpad -> Screenshot -> Options -> Other Location
** Key Modifers
System Settings -> Keyboard -> Keyboard Shorts -> Modifier Keys
** Mail
Mail -> Accounts -> Add Account
*** Google

mingmingli916@gmail.com
*** Microsoft Exchange
mili07@ulaval.ca
SOULart1107@*
*** QQ Mail
1. Visit the website https://wx.mail.qq.com/
2. Settings
3. Third-party Services
4. Generate Authorization Code
5. Input the generated code in the password column
** Add website to Dock
Safari -> File -> Add to Dock
** Control Center
System Settings -> Control Center

In this settings, you can configurate whether show the bluetooth in menu bar.

* Shortcuts


* Commands

