* 生活的意义
人类通过自己的行为来诠释生活的意义。

生活的意义因人而异，正因为如此，生活的意义多得不可胜数。

每一种个体认为正确的生活意义可能多少都包含错误的成分在里头。

人生的三大事实：
1. 我们生活在地球的表面。
2. 自己并不是人类种族的唯一成员，我们周围还有其他人，只要我们活着，就必然和他们发生联系。
3. 人类有两种性别。


所有的失败者之所以失败，就是因为他们缺乏归属感和社会兴趣。


属于私人的意义是完全没有意义的，意义只有在和他人交往时才有存在的可能。

人类的重要性是依赖他们对别人的生活所做出的贡献而定的。

所有真正的生活意义的标准时：它们都是共同的意义，就是说，它们是别人能够分享的意义，也是能够被别人认为有效的意义。

三种情景--器官缺陷，被骄纵，被忽视--最容易使人将错误的意义赋予生活。

* 心灵与肉体
预见运动的方向是心灵最重要的功用。

情感是依照他获取目标所必要的方向和程度而成长和发展的。

一只笨拙的右手是无法靠凭空妄想而变的灵巧的，它们只有通过练习才会变得较为灵活。

生活方式和其对应的情绪倾向，会不停的对身体发展施加影响。

* 自卑与超越
我们每个人都有不同程度的自卑感，因为我们都发现我们自己所处的地位是我们希望加以改进的。

没有人能长期地忍受自卑之感，它一定会使他采取某种行动来解除自己的紧张状态。

当个人面对一个他无法应付的问题时，他表示他绝对无法解决这个问题，此时出现的情绪便是自卑情绪。

由于自卑感总是会造成紧张，所以争取优越感的补偿动作必然会同时出现，但是其目的却不在于解决问题。争取优越感的动作总是朝向生活种无用的一面，真正的问题却被遮掩起来或避而不谈。

自卑感本身并不是变态的，它们是人类地位之所以增进的原因。

我们生活中的乐趣主要来自我们缺乏肯定性。

目标一改变，心灵的习惯和态度也会随之改变。

* 早期记忆
记忆绝不是偶然的，个人从他接受的，多得不可计数的印象中选出来的记忆，肯定是那些他觉得对他的处境极具重要性的事件。

患有忧郁症的人假如回想起他的成功和他的得意时光，他便不会再忧郁。

记忆绝不会和生活的样式背道而驰。只要他的生活样式发生改变，他的记忆也会随之改变。

当一个儿童心里充满对别人的敌意时，他绝不会在和别人的合作中扩展对他人的兴趣。

我们得到一种印象后，总是喜欢用它来解释其他事情。

行为的根源--早期记忆。

* 梦
人们经常相信左右是互相对立的，男女，冷热，光暗，强弱也是相互对立的。但是，从科学的立场看来，它们不是互相对立的食物，而是同一间东西的变异。它们是依照某种理想的假定排列而成的量表上的不同程度。

梦本身并没有什么重要性，重要的是梦后面的潜伏思想。

从科学的观点看来，做梦者和清醒时的人都是同一个人，梦的目的也必须适用于这个一贯的人格上。


对满足的追求只是千万种对优越感的追求之一，我们绝不能把它当作是各种人格表现的中心动机。

梦必定是生活样式的产品，它一定是有助于生活样式的建造和加强。

有一种事实能够帮助我们澄清梦的目的。我们做梦，但是清晨醒来后，我们通常都吧梦忘掉了，似乎不留一丝残痕。但这是真的吗？真的什么东西都没留下吗？不是的。我们还留有梦所引起的许多感觉。梦中景象都已消失，对梦的了解也不复存在，遗留下来的只有感觉。梦的目的必然是在于它们引起的感觉之中。梦只是引起这种感觉的一种方法，一种工具。梦的目标是它所留下的感觉。

个人所造出的感觉必须和他的生活样式永远保持一致。梦中思想和白天思想之间的差异不是绝对的，这两者之间并没有明显的界限。用简单的话来说，其间的差异仅在于做梦时有较多与现实的关系暂时被搁置了。然而，它并没有脱离现实。当我们睡觉时，我们仍然和现实保持着接触。

我们只有在消除了紧张而我们的问题也都有肯定的解决方法时，我们的睡眠才不会受到干扰。做梦是对安稳睡眠的干扰。

梦的工作就是应对我们面临的难题，并提供解决之道。

我们的心灵是用什么方法来应付问题的？
因为我们没有顾虑到整个情景，问题看起来便显得简单的多，而我们提出的解决之道对我们本身适应的要求也是非常之小。梦的目的是在支持生活样式，并引起适合于生活样式的感觉。但是，生活的样式为什么需要支持呢？有什么东西会侵袭它？能够攻击它的，只有现实和常识。因此，梦的目的就是支持生活的样式抵制常识的要求。如果一个人面临着一个他不希望用常识来解决的问题，他便能够用梦引起的感觉来坚定他的态度。


有些不愿意被他们的感觉所欺骗的人，他们宁可依照科学的方法做事，这种人很少做梦或者根本不会做梦。


在梦里，我们欺骗这自己。每一个梦都是自我陶醉和自我催眠，它的全部目的就是引起一种让我们准备应付某种问题的心境。

梦主要是有隐喻和符号构造而成的。假如我们不用隐喻和符号，而坦率的说出自己的意愿，我们便无法避开常识。

隐喻是非常美妙的语言工具，但是我们在运用它们的时候却难免要欺骗自己。

对一个拥有错误生活意义的人而言，运用隐喻和符号永远是一件危险的是。

一个人要跳过小溪流之前，可能要数一二三。难道数一二三真的这么重要么？在跳过溪流和数一二三之间真的有必要的关系存在么？不是的。他们一点关系也没有。他数一二三，只不过是要引起他的心境，并集中他的力量而已。在人类的心灵中，已经预存有执行生活样式，并使之固定和加强的各种方式，最重要的方法之一就是激发起心境的力量。

梦的目的是欺骗我们自己，并使我们自我陶醉。如果我们了解梦，它们便不能欺骗我们，再也不能引起我们的心境和情绪。我们宁可按照常识来解决问题，再也不愿意接受梦的启示。假如梦都被了解了，它们的目的也就丧失掉来 。

梦虽然有许多不同的变化，每一个梦却都表现出：依照个人面临的特殊情景，他觉得自己生活样式的哪一个方面需要再加强。


* 家庭的影响
母亲的技巧是否优良，影响了孩子的所有潜能。所谓母亲的技巧，指的是她和孩子合作的能力，以及她使孩子和她合作的能力。

即使我们遇到一个简单的问题，如果我们稍稍加以重视，也会比完全漫不经心好。

被宠坏的孩子通常都害怕单独一个人被留下，尤其是单独留在黑暗中。他们害怕的并不是黑暗本身，他们是利用害怕来使母亲跟他们跟接近。

对宠坏的孩子而言，疾病是求之不得的事。因为当他们害病时，他们会比平常更受到关注。

在母亲死掉之后，孩子可能会转向父亲，并受到他的关爱。现在，他觉得父亲的关怀被剥夺掉了，因此而攻击他的继母。

因为婚姻是伴侣式的结合，所以两个人都不应该想统驭对方。

没有人喜欢批评，但是假如一个人把逃避批评作为生活的中心点，那他跟社会的各种关系都会受到干扰。

作为父亲，他必须证明他对妻子，对儿子，以及对社会都是一个好伙伴。

不能以友善的方式进行的教育便是错误的教育。


做丈夫有一个重要条件：他必须对他的配偶深感兴趣。要看出一个人是否对另一个人有兴趣是很容易的事。如果他对她有兴趣，他对她喜好之物也会感兴趣，同时会把她的幸福当作是自己必须兼顾的目标。

一个家庭不应该过分强调金钱，或把金钱当作争执的题材。

父母任何一人都不应该表示他特别偏爱哪一个孩子。

假如父亲在他的行业中很有成就，他不应该在家庭中过分强调他的成功，否则孩子们的发展便会收到阻碍。

在家庭里，各成员都应该平等、合作、团结一致；家中不应该有敌对的感觉，也不应该让孩子觉得他有敌人并花费时间与之抗争，这样，才能避免不良的后果。

懒惰是野心再加上勇气丧失所得出的结果，野心高的使人看不出有实现的希望时，自然会令人心灰意冷。

* 学校的影响
教师要做的事情必须和母亲应该做的事情一样---和学生联系在一起，并对他发生兴趣。

教授课程最好的方法就是和生活中的其他部分紧密相连，是孩子们能够看出这种教导的目的和他们所学知识的使用价值。

在教育中引起最大困扰的，并不是儿童本身的各种限制，而是他认为他具有的各种限制。在教育的过程中，我们应该全力设法增加儿童的勇气和信心，并帮助他消除由于他对生活的解释而为自己的能力定下的各种限制。

我们最常犯的错误是相信我们再也无法进步了。我们看到别人遥遥领先，认为自己永远无法企及。

在教育中所犯的各种错误里，相信遗传会限制孩子们的发展是最糟糕的一种。

认为性格中有遗传成分的信念只能称为迷信而已。

当人们想要逃避责任，并对人类行为采取宿命论的观点时，性格特征是来自遗传的理论便自然而然的出现。

“善”“恶”，像其他各种性格的表现一样，只有在社会环境中才有意义。

心理功能发展中的最大因素是兴趣，能妨碍兴趣的，并不是遗传，而是灰心或对失败的畏惧。

在每种不平凡的能力后面，我们所看到的，并不是异乎寻常的遗传，而是长期的兴趣和训练。

假如教师相信孩子的发展有固定的限制，那么他便无法成功消除儿童为自己的发展定下的限制。

有些孩子只有在受到嘉奖或者赞赏时才肯学习。假如他们失去了这种特别的关怀，麻烦就来了。除非他们有观众，否则他们便无法获得进展；如果没有人注视他们，他们的兴趣就会随之而止。这似乎是一种小毛病，但是对我们共同生活造成最大危险的，就是这些终日要求别人注意和支持的孩子。

有些孩子，他们决心要成为众人注意的中心，假如不能如愿，他们便会搞恶作剧，扰乱班上的秩序，带坏其他孩子。责备和惩罚都改变不了他，这些正式投其所好。他宁可受痛打，也不愿被忽视。

懒惰的孩子，除非他的懒惰是对父母或者老师的直接攻击，否则他们几乎都是野心勃勃而又怕遭到失败打击的儿童。懒惰的孩子从未尝过被击败的滋味，因为他从没有面临真正的考研。他对眼前的问题总是尽量逃避，而不肯轻易和人一较长短。

“只要我肯做，哪件事我做不了？”当他失败时，他也会以此自我嘲解，并保持他的自尊。他会对自己说：“我知识懒，不是无能。”

假如他不费吹灰之力便能获此殊荣，他为什么要努力工作，冒失去被人重视的险？很可能如果他不再懒惰时，人家便不会再以为他怀才不露了。别人会以他的成就来评判他，而不在重视他可能达成的成就。懒孩子得到的另一点好处就是，当他做了一点点工作时，别人就会夸奖他。别人看到他好像有洗心革面的意思，便急着想刺激他痛改前非。同一件工作，假如是勤快的孩子所做，便不会受到这么多的重视。懒孩子便以这种方式生活在别人的期待里。他也是个被宠坏的孩子，从婴孩时代起，他便学会不管什么事都期待别人帮他完成。

有些孩子喜欢在同伴中起带头作用。大部分扮演领袖角色的儿童所感兴趣的，只是能让他们统驭别人的情景。只有在这种情况下，他们才肯参加同伴的活动。

有远大的理想和希望自然是件好事，但是如果没有找到合适的方法，空谈理想也是没有用的。

* 青春期
青春期把正在成长的孩子带入新的情景，接受新的考验。

对每个孩子而言，青春期中最重要的一件事情就是他必须证明他已经不再是哥孩子了。

青春期有许多种行为都是出自想表现独立性、和成人平等、男子气概或女人作风等等的欲望。这些表现的方向取决于儿童对“成长”的意义抱有何种看法。

我们无法给青春期的阶段定下严格的界限。它通常是由14岁左右到20岁左右，但是有些孩子在十一二岁时便已经进入青春期了。

犯罪是从生活问题面前逃离掉的简捷方法之一，特别是在经济问题之前。

如果个人的活动程度较小，他逃避生活问题的简捷方式是神经病。

每一种神经病的病症，都是不必降低个人的优越感而拒绝解决生活问题的接口。神经病出现在个人面临社会性问题，而又不准备以符合社会要求的方式来解决他的时候。

器官的不适也可以作为犹豫和失败的脱身之词。在这类个案中，个人不管是私下还是在他人面前，都会因为他的病痛，而认为自己可以不必承担任何责任。这样便构成了神经病。每一个神经病患者都表现了最诚挚的意愿，他十分了解社会感觉和应付生活问题所需有的是什么，只有在他的病症里，他才能逃避这种普遍的要求。

重要的是个人在这个阶段中所期待的是什么，他们赋予他的意义，和他学会的面对它的方法。

如果一个孩子已经学会把自己当作是和社会上任何人平等的一份子，并了解他应该做的奉献工作，尤其是如果他已经学会将异性看作是平等的友伴，青春期只是给他一个机会，让他开始对成年人的生活问题做出独立而有创造性的解答。

* 犯罪及其预防

罪犯都是在处理生活问题时遭遇了失败，特别是在一个令人注意的固定点上，他们完全陷于失败。

我们都希望克服苦难。我们都努力着，想着要在未来实现某一个目标，实现它，我们将会觉得自己强壮、优越、完美。


在罪犯的各类活动和态度中，都显现出他也是努力成为优秀的人物，要解决问题，有克服苦难。他们和普通人的不同之处并不在于他没有做这种形式的追求，而是他所追求的方向。

每一个罪犯都遵循着这条主线在追求胜利，在追求固定的地位。我们发现罪犯的目标总是在追求属于他私人的优越感。他所追求的，对别人一点贡献都没有，他也不和别人合作。

假如我们要了解一个罪犯，我们要找出的主要点也他在合作中失败的程度和本质。

生活的样式体现了一个人的人格，只有了解一个人在建造自己的生活样式时犯了什么错误，他才有可能改变过来。

人们的行为是收到限制的。

最重要的是生活样式，也就是应付问题的方法。

罪犯对别人都不感兴趣，他们只有有限的合作能力，超过这个限度时，他便开始犯罪。

在我们的一生中，除了社会问题以外便没有其他问题，而这些问题是在只有我们对别人感兴趣时才能获得解决的。

个体心理学告诉我们，生活的问题可以分成三大类。
- 与其他人之间关系的问题，也就是友谊的问题。
- 包括与职业有关的各种问题。
- 包括了所有的爱情问题。


当我们说话的时候，我们总希望每个人都能了解我们。了解本身就是一种社会因素。我们给予语言的一种共同的解释；我们理解他的方式，应该是和任何其他人都一样的。但是罪犯们就不是这样了，他们有私人的逻辑和私人的智慧。他们对这个世界有一种错误的看法，他们对自己的重要性和别人的重要性也有一种错误的估计。

罪犯全部都是懦夫。他们逃避了他们觉得自己的能力不足以应付的问题。

罪行是懦夫模仿英雄行径的表现。他们在追求着一种自己构想出来的个人优越感目标，他们以为自己是英雄，但其实这又是一种错误的统觉表，也是缺少常识的表现。

我们必须打破罪犯对其勇气和机智的评判方法。

妒忌绝不会产生有价值的目标。


当父母在子女面前抱怨生活艰难、世道险恶时，他们也会妨碍孩子社会兴趣的发展。


教孩子合作就像教他们地理课一样，因为它是一种真理，真理必然是可以传授的。不管是成人还是儿童，假如他没有充分准备就去参加地理科目的考试，他必然会遭到失败。同样的，不管是成人还是儿童，假如没有充分的准备，就到一个需要合作的情景去接受考验，那么也会一败涂地。


罪犯在开始筹划犯罪时，一般都是深处困境，他没有勇气以合作的方式来面对问题，而是想找一个比较简单的解决方式。

* 职业
束缚人类的三条系带构成了人类的三个问题：
- 职业问题
- 与他人相处及合作的问题
- 两性关系问题

这三个问题是不能分开来解决的，要解决任何一个问题都依赖与其余两个问题的顺利解决。解决了一个问题必定有助于另一个问题的解决。

假如我们想解决职业问题，我们就必须在人类分工合作的架构中占据一席之地，并且为别人的利益奉献出我们的力量。

早一点问孩子希望从事哪一种职业是很有好处的。

如果在家庭生活中过分强调金钱的价值，孩子们会只凭收入的多寡来看待职业的问题。

* 人及其同伴

人类最古老的努力之一，是和其同类缔结友谊。我们的种族是由于我们对我们的同类有兴趣才日渐进步的。

最简单的原始宗教是图腾崇拜。

基督教中最重要的教诲之一是“爱你的邻居”。

各种不同的宗教都以自己的方式鼓吹着合作。

最高程度的孤立可以用疯狂来代表。如果能引起他们对别人的兴趣，即使是疯狂也不是无可救治的。

妄想狂和忧郁症这两种情况都能够清楚地显现出他和别人之间的距离。妄想狂的病人埋怨着所有的人类，他认为他四周的人都沆瀣一气，想来陷害他。忧郁症的病人会自怨自哀，然而，一个人在责备自己时，只是他表现出来的外貌，其实他是在责备别人。

忧郁症是对别人长期的愤怒和责备，由于想要获得被人的照顾、同情和支持，病人只好为他自己的罪过表现的垂头丧气、痛心疾首。


“不要做你不喜欢的事情”，如果忧郁症患者能够随心所欲地做任何事情，他还会控诉谁呢？

在这个世界真的有许多邪恶、困难、偏见和悲哀，但这是我们自己的世界，他的优点和缺点也是我们自己的优点和缺点。这是我们必须加以改造和增进的世界。


* 爱情和婚姻
爱情，以及其结果的婚姻，都是对异性伴侣最亲密的奉献，它表现在心心相印、身体的吸引，以及生儿育女的共同愿望中。

美好的婚姻是我们养育人类未来一代的最好方法。

任何一种严肃而重要的生活或者工作，都是不能先替自己安排脱身之计的。

假如夫妻两人都要保留个人的自由，真诚的爱情关系就没有实现的可能。

如果配偶真正对彼此感兴趣， 他们便不会遇到性的吸引力全然消失的困难。

如果性的功能有了缺陷，必定是这两个人之间未能真正地协调一致。

*夫妻是平等的伙伴关系*。
