:PROPERTIES:
:ID:       8CD9893F-A801-41FF-986C-53F6AEC47748
:END:
#+title: economy

* 经济学十大原则
** 决定
*** 原则1: 取舍
资源包括时间、金钱、精神、身体、人际关系等等你所拥有的一切。

我们想要获得某些东西的时候，必然需要耗费我的某些资源。
这部分资源如果用于某个目的，则不然不能用于其他目的。

比如：
我们花时间来学习经济学，而这部分时间就不能用来玩游戏，学习编程，维系人际关系等等。

*** 原则2: 机会成本
我们花费资源来达到某种目的，这部分资源如果用来做其他的事情所获得的收益就是我们所浪费掉，这些收益就是我们的机会成本。
因为如果我们不利用这部分资源，我们本来是有机会获得该收益的。

比如：
我们选择上学，那我们所花掉的时间和金钱等等，如果用来做其他的，比如找工作，创业，做运动员等等所获得的收益就是我们的机会成本。

*** 原则3: 边际思维
在既定事实的情况下，做微小的改变，称为边缘变化。

在边缘变化下，如果收益大于成本，我们就是付诸行动。

比如：
航班总是要飞行，空座以很低的价格卖出，收益大于成本，
因为这个时候的成本仅仅是多出几个餐钱，座椅的磨损等几乎可以忽略不计，但收益确是可观的。
*** 原则4: 无利不起早

这个利可以是金钱，时间，物质，兴趣，声望等等。

比如：
软件行业的培训，因为软件行业的高薪资催生了软件培训的需求，软件培训有大利可图。
** 交互
*** 原则5: 贸易
贸易使我们可以深研某一个方面。
比如：
我们不用学习很多种植粮食的知识，我们可以买粮食。
我们不必需要很多电脑组装的知识，我们可以购买整体的电脑。
人们有的以法律谋生，有的以软件谋生，有的以种植谋生，我们只需要某一个领域比大多数人强，就可以在该领域以自己的知识或者技能谋生。
*** 原则6: 市场通常是组织经济活动的好方法
市场经济中，公司决定雇佣谁并决定生产什么，消费者决定为哪家公司工作并决定用自己挣得钱买什么。
公司和消费者是市场的切实参与者，他们更清楚需要生产什么或者需求什么？
价格是调整资源流向重要方式。
*** 原则7: 政府有时可以改善市场
政府的一个重要作用是保证所有权。
只有在保障所有权的前提下，我们才愿意去争取更多的财富，因为这些财富可以为我们所有，我们对这些财富有所有权。

政府的另一重要作用是保证资源分配的平均性。

利益的最大化有时候会忽略长远的影响，比如污染，这个时候就需要政府制定政策来控制污染。

垄断也不利于市场的资源有效流动。
** 整体
*** 原则8: 生活水平取决于生产力

*** 原则9: 当政府印太多钱时价格就会上涨
*** 原则10: 社会面临通货膨胀和失业之间的短期权衡

