* 1. THE COMPLETE MUSICIAN
Your success as a musician depends on your ability to hear music, to know what you are hearing, to remember what you have heard, and then to communicate through music notation or performance.

The world's music, however diverse, shares common elements.
The unique attributes of each culture/genre/style are merely variations of intervals, rhythms, temperament and timbre.

You can reach a level of perception that will enable you to recognize and notate any musical sound, which in turn will allow you to develop unlimited compositional or improvisational abilities.

** THE GOAL
Your job, like any artist or craftsman, is to know your materials intimately and to be aware of all the possibilities inherent in them.

1. Perceive and notate any style of music.
2. Remove obstacles to composition or improvisation.
3. Communicate accurately through music notation.
4. Develop a fast sketch technique.
5. Be able to jot down an idea anywhere, without using an instrument.
6. Document and preserve your work.
7. Consolidate your skills into an integrated, subconscious process.

PERCEPTION:
A MENTAL IMPRESSION RECEIVED THROUGH THE SENSE;
COMPREHENSION OF THAT RECEIVED;
UNDERSTANDING;
AWARENESS;
INSIGHT.

** THE METHOD
the fundamental skills of creating music: hearing and writing.
1. inhale music
2. process music
3. exhale music


As you work with music, your decisions are guided by your instincts and experience, rather than by concrete rules.
When composing, be the listener; when orchestrating, be the composer; when copying or conducting, be the performer.

The perception/notation process ties together all the disciplines in the music making process, from the inner world of feeling and the thought to the outer world of performance and production.

Learning music is a very personal experience. Once you have it, you own it for life.

** MUSIC TERMINOLOGY
A musician's training includes sorting out, accepting and rejecting concepts as well as the words that define them.
Your goal is to ultimately eliminate words from the process of perception.
When you are actively hearing and writing music, the words will no longer be needed -- music will flow through you to become symbols and sounds.

** PERSONAL TRAINING
Music is a continuing process of discovery and development.
Inspiration happens in an instant; the craft is developed over one's lifetime.

Music, like all art, is ultimately self-taught.
The energy required can only be generated by your passion, curiosity and love for music.

Music has no boundaries. It is yours to discover, to enjoy, to draw from and to pass on others.


* 2. DEVELOPING YOUR EAR
** PERCEPTION
Music is the only art that is intangible.
As musicians, we work with a very abstract medium; if you can't see or touch sound, how you can manipulate it to create music?
By developing two skills:
1. Active listensing: knowing what you are hearing at any given moment.
2. The ability to re-create what you are hearing or thinking -- spontaneously, with an instrument, your voice, or with the symbols of music notation.

An important concept in this training is to make a distinct separation between the hearing process and the writing process.
To clarify the distinction, we'll use the word tone only when we're referring to a sound and the word note only when we're referring to a symbol.

tone <--> sound
note <--> symbol

We all have the same equipment for perception of sound --ears and brain-- so music, traveling through the air, reaches everyone in the same manner.
At the point of perception, sound assumes meaning or trigger emotions -- becomes a personal experience.
We evaluate what we hear though our own set of filters.
Your filters include all the music you've heard, your cultural background, your understanding of music theory, your comprehension of acoustics, your knowledge of instruments and your emotional state and receptive awareness.
When woking with music, we try to listen with open objective ears, yet call on our experience as we make musical decisions.

Separating the fundamental activities of hearing and writing music will allow you to give full concentration to each.
When you are fluent and comfortable, they will be combined to produce a technique that is accureate, fast and efficient.

     Listening is the primary musical activity. The musician listens to his own idea before he plays, before he writes.


** ACTIVE LISTENING
The best training for all phases of music making is active listening.

Most sounds that enter your ears are unconcious.
You can develop a concious awareness of external sounds and use those sounds to practice identifying intervals, rhythms and timbre.
There is always something new to discover, for there are sounds happenning all around you.
Even non-musical sounds contain the essence of music, for music is just organized sound.

     All sounds are music; any sound can be a part of a piece of music.
     Enjoy sounds of your environment; you don't have to understand, simply experience.
